apiVersion: v1
kind: Service
metadata:
  name: swagger-proto
  labels:
    app: swagger-proto
spec:
  selector:
    app: swagger-proto
  ports:
    - name: grpc
      port: 8080
      # nodePort: # Optional field by default and for convenience, the Kubernetes control plane will allocate a port from a range
      protocol: TCP
      targetPort: 8080
  type: NodePort