// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/v1/user.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateUserResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eeaf71090dd90b5, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetUserResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user.v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.v1.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user.v1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.v1.GetUserResponse")
}

func init() {
	proto.RegisterFile("user/v1/user.proto", fileDescriptor_6eeaf71090dd90b5)
}

var fileDescriptor_6eeaf71090dd90b5 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0xda, 0xe2, 0x1e, 0x2c, 0x0e, 0x85, 0x86, 0xe8, 0x41, 0x72, 0xd2, 0x62, 0xb3,
	0x54, 0x6f, 0x1e, 0xf5, 0x50, 0xbc, 0x16, 0xbd, 0x08, 0x22, 0xdb, 0x64, 0x48, 0x17, 0x9a, 0xdd,
	0x74, 0x77, 0x5b, 0x28, 0xe2, 0x45, 0xfc, 0x03, 0x3f, 0xc7, 0xcf, 0xf0, 0x17, 0xfc, 0x10, 0xc9,
	0xa6, 0x0d, 0x2d, 0x4d, 0xf1, 0x94, 0x7d, 0x6f, 0x5f, 0x66, 0xdf, 0x9b, 0x19, 0x02, 0x0b, 0x8d,
	0x8a, 0x2e, 0x87, 0xb4, 0xf8, 0x46, 0xb9, 0x92, 0x46, 0x42, 0xdb, 0x9e, 0x97, 0xc3, 0xe0, 0x2c,
	0x95, 0x32, 0x9d, 0x21, 0x65, 0x39, 0xa7, 0x4c, 0x08, 0x69, 0x98, 0xe1, 0x52, 0xe8, 0x52, 0x16,
	0x66, 0xe4, 0xe4, 0x5e, 0x21, 0x33, 0xf8, 0xa4, 0x51, 0x8d, 0x71, 0xbe, 0x40, 0x6d, 0x00, 0x88,
	0x27, 0x58, 0x86, 0xbe, 0x73, 0xee, 0x5c, 0x1c, 0x8d, 0xed, 0x19, 0xba, 0xa4, 0x89, 0x19, 0xe3,
	0x33, 0xbf, 0x61, 0xc9, 0x12, 0x14, 0x6c, 0x3e, 0x95, 0x02, 0x7d, 0xb7, 0x64, 0x2d, 0x00, 0x9f,
	0xb4, 0x59, 0x92, 0x28, 0xd4, 0xda, 0xf7, 0x2c, 0xbf, 0x81, 0xe1, 0x80, 0xc0, 0xf6, 0x73, 0x3a,
	0x97, 0x42, 0x23, 0xf4, 0x88, 0x75, 0xfb, 0xca, 0x13, 0xfb, 0xa4, 0x3b, 0x6e, 0x15, 0xf0, 0x21,
	0x09, 0x2f, 0xc9, 0xf1, 0x08, 0xcd, 0xb6, 0xb5, 0x83, 0xd2, 0x4f, 0x87, 0x74, 0x2a, 0xed, 0x3f,
	0x75, 0xab, 0x80, 0x8d, 0xba, 0x80, 0x6e, 0x6d, 0x40, 0xef, 0x40, 0xc0, 0xe6, 0x4e, 0xc0, 0xeb,
	0x6f, 0x87, 0x78, 0x85, 0x07, 0x78, 0x21, 0xad, 0x32, 0x29, 0x04, 0xd1, 0x7a, 0x14, 0xd1, 0x5e,
	0xa7, 0x83, 0xd3, 0xda, 0xbb, 0xd2, 0x7e, 0x18, 0x7c, 0xfc, 0xfc, 0x7e, 0x35, 0xba, 0x61, 0x67,
	0x33, 0x5a, 0x1a, 0x5b, 0xd1, 0xad, 0xd3, 0x87, 0x47, 0xe2, 0x8e, 0xd0, 0x40, 0xaf, 0xfa, 0x7f,
	0xb7, 0x4f, 0x81, 0xbf, 0x7f, 0xb1, 0x5b, 0x15, 0xa0, 0xaa, 0xfa, 0xb6, 0x6e, 0xd2, 0xfb, 0xdd,
	0xd5, 0x73, 0x3f, 0xe5, 0x66, 0xba, 0x98, 0x44, 0xb1, 0xcc, 0x68, 0x3c, 0x5d, 0xf1, 0x15, 0x9b,
	0x73, 0x91, 0xd2, 0x34, 0xe3, 0xb1, 0x92, 0x03, 0xbb, 0x33, 0x74, 0xbd, 0x6d, 0x93, 0x96, 0x85,
	0x37, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x79, 0xf8, 0x82, 0x7f, 0x02, 0x00, 0x00,
}
